### ISSUE TITLE
Change Light entity icon

### ISSUE THREAD

**Issue by johanvh83** [Mariusthvdb/custom-ui#34]
Dear Marius,

I have many light entities. When a lovelace entity card is used the icon changes depending the brightness of the bulb.

Brightness 0 is translated into a white icon, 255 becomes a light blue icon.

Is it possible by your custom-ui to change it globally so all light entities to a custom color change.
I mean if brightness = 0 = black icon -> 255 = white icon

Thanks in advance,

**Comment by Mariusthvdb** [comment]
anything is possible I guess, but the techniques would vary. I take it you want to use this on a regular entities card listing?

If so, try to customize on the `attributes.brightness`

```
if (attributes.brightness) return 'etcetc';
```

but I still dont get it because the light icons already change according to brightness:

<img width="474" alt="Schermafbeelding 2021-02-10 om 09 17 35" src="https://user-images.githubusercontent.com/33354141/107483179-fe37fc80-6b80-11eb-8a31-75d68d5cb953.png">
<img width="478" alt="Schermafbeelding 2021-02-10 om 09 17 43" src="https://user-images.githubusercontent.com/33354141/107483185-fed09300-6b80-11eb-9fb8-d6f99ff9155d.png">
<img width="470" alt="Schermafbeelding 2021-02-10 om 09 17 53" src="https://user-images.githubusercontent.com/33354141/107483186-ff692980-6b80-11eb-8c6d-84a4b7f4d996.png">
<img width="472" alt="Schermafbeelding 2021-02-10 om 09 18 01" src="https://user-images.githubusercontent.com/33354141/107483187-ff692980-6b80-11eb-8175-9b62c02015ac.png">
<img width="476" alt="Schermafbeelding 2021-02-10 om 09 18 09" src="https://user-images.githubusercontent.com/33354141/107483190-ff692980-6b80-11eb-9b2f-c66ea0a80583.png">
