### ISSUE TITLE
Slow loading of customizations

### ISSUE THREAD

**Issue by m1ke-hub** [Mariusthvdb/custom-ui#38]
Hey Marius, I hope you are doing well!

Since a few days - at least I didn't notice earlier - the customizations sometimes take a long time (5-10 sec.) to load.
This happens when I reload (F5) a page on my Windows PC in Edge and Firefox, but not on the iOS companion app.

Are you guys experiencing similar problems?

**Comment by Mariusthvdb** [comment]
no not really, but did a lot of tweaking lately to the resource... and of course updated HA. SO, to begin with, which versions are you running?

**Comment by migo-dev** [comment]
Everything is up-to-date (HA 2021.5.3 & custom-ui 2021.05.11)

Correction: It's also happening on my iPhone, but only when swiping down to reload..

I will downgrade to "1 month ago" and see if the problem was already there, but I didn't notice. Will report back here.

**Comment by Mariusthvdb** [comment]
Ok let us know please, because it is immediate here, on the most customized Ha instance I use.

**Comment by migo-dev** [comment]
So I was able to test this today. I went back to HA 2021.04.6 & custom-ui 20210409, cleared browser cache - and the customizations were always applied instantly (or a split-second) after reloading the page.

When I went back to up-to-date, cleared cache again - the problem returned immediately. BTW Here's how it looks like:

https://user-images.githubusercontent.com/57773976/118265798-0114f700-b4ba-11eb-9eb0-67e45e9d0211.mp4

As you can see, sometimes it's instantly, but sometimes it takes pretty long.. I've seen even way worse than the third reload in the video. I know, who tf reloads pages that often - it was only for demonstration purposes to show how it differentiates (it also happens when I only reload once).

**Comment by Mariusthvdb** [comment]
this is a bit difficult to check, it can be many things in a system. As said, in my 3 configs, they all respond as before. Maybe its Windows? I don't have that, so can't test.

Do you have anything in the inspector Console log indicating a problem?

**Comment by migo-dev** [comment]
> Do you have anything in the inspector Console log indicating a problem?

I don't think so - but then again I don't really know what to look for to be honest.

> Also, did you check another browser? Chrome maybe?

Yes, just tested in Chrome, same slow behaviour as in Firefox and Edge. Also dusted off my old MacBook to check on there - same thing in Chrome and Safari. In my case it happens in storage & yaml mode - where yaml is even worse.

**Comment by Mariusthvdb** [comment]
is it only on reload of the page, or also on state change?

**Comment by migo-dev** [comment]
It does only happen on page-reload - so switching views is usually no problem at all, as well as state changes. When I for example turn on a light, while the customizations are not applied yet, it immediately applies all of them.

Well haha, I barely have 300 entities, most of them either have the icon, icon_color or unit_of_measurement customized - but not all are templates. My customize_glob.yaml has ~650 lines.

Here's how my templates usually look like:
```
sensor.update_addons:
  icon: "mdi:home-plus"
  friendly_name: "Update Addons?"
  templates:
    icon_color: if (state === '0') return '#444444'; else return '#aeaeae'
    unit_of_measurement: if (state === '1') return 'Update'; else return 'Updates'
```
I'd say, the most customized are my lights (as I have added a templated attribute), which look like this:

```
light.all:
  templates:
    icon: if (state === 'on') return 'mdi:lightbulb-group'; else return 'mdi:lightbulb-group-off';
    icon_color: >
      if (attributes.brightness < 51) return '#666666';
      if (attributes.brightness < 111) return '#858585';
      if (attributes.brightness < 162) return '#aeaeae';
      if (attributes.brightness < 223) return '#d1d1d1';
      if (attributes.brightness < 256) return '#ffffff';
      return '#444444';
    brightness_pct: >
      var brightness_percent = Math.round(100/255*Number(attributes.brightness));
      return brightness_percent;
```

**Comment by Mariusthvdb** [comment]
that doest seem to be that special ;-)

only thing I always do is replace the '===' with '==', and leave out the 'else'.
Also, always delimit the template with a ';' 

```
  templates:
    icon_color: if (state === '0') return '#444444'; else return '#aeaeae'
    unit_of_measurement: if (state === '1') return 'Update'; else return 'Updates'
```

would then become:
```
  templates:
    icon_color: if (state == '0') return '#444444'; return '#aeaeae';
    unit_of_measurement: if (state == '1') return 'Update'; return 'Updates';
```

the first 2 probably wont matter, but the latter might. please add that everywhere, just in case.

**Comment by migo-dev** [comment]
Right?! :-)

Thanks a lot for these suggestions - I really appreciate your help! Just employed them, but unfortunately it did not solve the problem..

I guess, I will start another HA instance later today and test everything thoroughly in there..

**Comment by cschillings** [comment]
> 
> 
> Right?! :-)
> 
> Thanks a lot for these suggestions - I really appreciate your help! Just employed them, but unfortunately it did not solve the problem..
> 
> I guess, I will start another HA instance later today and test everything thoroughly in there..

Had the same issue after one of the last HA Core updates, fixed it with uninstall and reinstall custom-ui.

**Comment by Mariusthvdb** [comment]
I see this too now, in 2 of my 3 instances.
The one still responding immediate is the biggest instance though, with many thousands of customizations. SO I suppose it isnt that. 
I have an instance with only the ZwaveJS server add-on and only a few entities/devices, and it is displaying that mentioned behavior of slow loading customizations.

Would be good to know if you see the issue too, only reverting the 2021.4.6 to see if the frontend has changed anything that could affect this, and then I could ask Bram or Philip with a direct lead.

**Comment by m1ke-hub** [comment]
Yep, I still see the same behaviour, now on 2021.6.0b6. I did not find the time to install an additional instance for testing yet, though. The lack of icons in this beta round made me somewhat forget about this a bit 😉

**Comment by Mariusthvdb** [comment]
update:

since people in the community are reporting timing issues on recorder, I checked to see whether this could be casing the slow loading too. I had already been drawn in that direction, because when one checks the network tab in the inspector window, you can see the customizations kick in, and it is after quite a wait sometimes.

so first I disabled several add-ons, without effect. Then, I turned to MariaDB, which is supposed to have better handling of the DB than the default SQLLite. And DuckDns. This has a huge effect on the timing of the customizations.

Still this made no sense to me, as I have both running on my main instance, which acts perfectly as ever. I then realized, my main instance has a carefully curated include list of recorded entities, domains and services.

So I did copied th over to my troubled instance, et voila, much better indeed. Still not as before, (which didn't filter the recorder) but much better. Guess we're on to something in the backend with the DB handling.

Please give that a try too, to see if things get better on your side.

**Comment by m1ke-hub** [comment]
Thanks a lot for the update, Marius! Don't get me wrong, but I somewhat feel relieved it also started happening to you 😉 

I just did some tests where I simply inverted my "10-entities-long" exclude list to an include list. But that did not improve it at all - so I also tried removing the MariaDB url and going with the standard DB, which sadly did not work either. I did not create extensive lists like yours, so that might be explaining the different results - but I was under the impression that if you include only certain things, everything else will be excluded. Will definitely copy and adapt your recorder configurations for more similar pre-conditions in the next few days and report back!

**Comment by unknown0816** [comment]
I guess I have a similar issue. I installed custom-ui via lovelace resource (UI) and the changes worked, but every time I reload the page all the changes were not visible. I have to actively use entities to get the correct behavior. 
However, I just tried to install custom-ui in the configuration.yaml in the frontend: section and voila it works fine.

I don't know if this is a different issue, or if this behavior is already known, but I thought I share my experience.

**Comment by Mariusthvdb** [comment]
the sow loading seems to have improved a lot lately, and that must have been because of changes in HA, because I havent touched Custom-ui since a longer time now ;-)

the install method suggestion you bring up is interesting, Ill have a look at that most certainly, thanks for that!

I recognize the need for states to change before the customization kicks in, although that isnt always the case. Never bothered me though tbh. Seems fair that it only does kicking upon the next change after the reload doesnt it?

**Comment by Mariusthvdb** [comment]
separate post, so everyone sees this.
please check https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2293 where Thomas explains about changes in card-mod and suggest setting up via
```
frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
```

> you can give card-mod a head start.

seems @unknown0816 noticed the same behavior ? interesting, I didn't know about that.

**Comment by Mariusthvdb** [comment]
let's close this now.

**Comment by patrickli** [comment]
> separate post, so everyone sees this. please check https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2293 where Thomas explains about changes in card-mod and suggests setting up via
> 
> ```
> frontend:
>   extra_module_url:
>     - /hacsfiles/lovelace-card-mod/card-mod.js
> ```
> 
> > you can give card-mod a head start.
> 
> seems @unknown0816 noticed the same behavior ? interesting, I didn't know about that.

I know this is closed, but I did have performance issues with this plugin until I put it in `extra_module_url`. It now applies the customizations almost instantly.
