### ISSUE TITLE
Tons of errors in HA 0.111.1

### ISSUE THREAD

**Issue by mfabiani53** [Mariusthvdb/custom-ui#4]
After upgrading to 0.111.1 i get tons of these errors.
```
2020-06-12 14:41:45 ERROR (MainThread) [frontend.js.latest.202006032] https://192.168.1.24:8123/local/custom-ui/custom-ui.js?v=20200528:31:16122 Uncaught TypeError: Cannot read property 'state' of undefined
```
And they stop just after the UI frontend loads completely.
I noticed you updated custom-ui.js 3 days ago and installed latest release…

**Comment by Mariusthvdb** [comment]
And your question is?

If it’s about the new errors in Ha0.111 see https://community.home-assistant.io/t/0-111-frontend-loaded-sooner-elexa-guardian-unify-circuit-acmeda/203753/136?u=mariusthvdb

You probably have unguarded templates.

**Comment by mfabiani53** [comment]
My question is how to get rid of those errors?
What you mean with "unguarded templates" ?

**Comment by Mariusthvdb** [comment]
Please read the post in the link.

You are customizing states that are not (yet) available.
You should guard these for existence.

**Comment by mfabiani53** [comment]
Yes ok i understand but don't know how to "guard" those states. Maybe it's my poor english....

**Comment by Mariusthvdb** [comment]
You haven’t given us an erroring template yet...
There’s an example in the link I provided

**Comment by mfabiani53** [comment]
But i cannot know which template is bad as before the latest release of HA all was working good...
Give me some hints about where to begin to check my templates...
As i told you before, when the UI frontend is completely loaded the errors stop and all my templates are working....

**Comment by Mariusthvdb** [comment]
you're on your own here, I can't check all of your templates ;-)

as in the example, the issue is when a template references another entity that hasn't been initialized yet during startup. That is also the reason they disappear after startup.

in my case, the offending entity was displayed in the home-assistant.log you re sure there's nothing there in the log?

```
person.marijn:
      templates:
        entity_picture: >-
          if (entities['sensor.marijn_picture']) return entities['sensor.marijn_picture'].state;
          return '/local/family/marijn_not_home.png';
```

`person.marijn` is customized following the state of another entity, `sensor.marijn_picture`. So, I added the guard for its existence, and an 'else' clause:

```
 if (entities['sensor.marijn_picture'])
```

to the template I used before
```
person.marijn:
      templates:
        entity_picture: >-
           return entities['sensor.marijn_picture'].state;
```

**Comment by Mariusthvdb** [comment]
this can be closed now.
